/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OCRS;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author audrey
 */
public class admin_addCourse extends javax.swing.JFrame {

    /**
     * Creates new form admin_addCourse
     */
    public admin_addCourse() {
        initComponents();
    }
    public admin_addCourse(String uname) {
        initComponents();
        usr_lbl.setText(uname);
        usr_lbl.setVisible(false);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseDet_Label = new javax.swing.JLabel();
        courseidLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        cIDText = new javax.swing.JTextField();
        cNameText = new javax.swing.JTextField();
        feeText = new javax.swing.JTextField();
        levelComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();
        courseDescriptionLabel = new javax.swing.JLabel();
        courseDesc_Text = new javax.swing.JTextField();
        usr_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseDet_Label.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 24)); // NOI18N
        courseDet_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseDet_Label.setText("Add Course Details");

        courseidLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        courseidLabel.setText("Course Name:");

        courseNameLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        courseNameLabel.setText("Course Code:");

        levelLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        levelLabel.setText("Level:");

        feeLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        feeLabel.setText("Fee:");

        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select course level", "Level 1", "Level 2", "Level 3" }));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        backLabel.setText("Back to Course List");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLabelMouseExited(evt);
            }
        });

        courseDescriptionLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        courseDescriptionLabel.setText("Course Description:");

        usr_lbl.setText("(placeholder for username)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usr_lbl)
                .addGap(61, 61, 61)
                .addComponent(backLabel)
                .addContainerGap())
            .addComponent(courseDet_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courseDescriptionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(courseDesc_Text)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseidLabel)
                            .addComponent(courseNameLabel)
                            .addComponent(levelLabel)
                            .addComponent(feeLabel))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cNameText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cIDText)
                                    .addComponent(levelComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(feeText, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 153, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backLabel)
                    .addComponent(usr_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseDet_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseidLabel)
                    .addComponent(cIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseNameLabel)
                    .addComponent(cNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feeLabel)
                    .addComponent(feeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courseDesc_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courseDescriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(resetButton))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        String uname = usr_lbl.getText();
        String profile = "Admin";
        List_Courses lc = new List_Courses(uname, profile);
        lc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    private void backLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseEntered
        // TODO add your handling code here:
        Font original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_backLabelMouseEntered

    private void backLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseExited
        // TODO add your handling code here:
        Font original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_backLabelMouseExited

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        try{
            cIDText.setText("");
            cNameText.setText("");
            levelComboBox.setSelectedItem("Select level of course");
            feeText.setText("");
            courseDesc_Text.setText("");
        }
        catch(Exception res){
            JOptionPane.showMessageDialog(null, res+"system error");
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String coursen, coursec, lvl, coursed;
        int fee = 0;
        
        coursen = cNameText.getText();
        coursec = cIDText.getText();
        lvl = levelComboBox.getSelectedItem().toString();
        try{
            fee = Integer.parseInt(feeText.getText());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a correct fee amount.");
        }
        coursed = courseDesc_Text.getText();
        
        if (coursen.length() == 0 ){
            JOptionPane.showMessageDialog(null, "Please enter course name.");
            return;
        }
        else if (coursec.length() == 0){
            JOptionPane.showMessageDialog(null, "Please enter course code.");
            return;
        }
        else if (lvl.equals("Select course level")){
            JOptionPane.showMessageDialog(null, "Please select course level.");
            return;
        }        
        else if (fee < 10){
            JOptionPane.showMessageDialog(null, "Course fee can not be less than 10, please enter an appropriate fee.");
            return;
        }
        else if (coursed.length() == 0){
            JOptionPane.showMessageDialog(null, "Please enter course description.");
            return;
        }
        String fee2 = Integer.toString(fee);
        Add_del_mod_course admc = new Add_del_mod_course();
        admc.addCourse(coursen,coursec,lvl,coursed,fee2);
        resetButton.doClick();
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_addCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_addCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_addCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_addCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new admin_addCourse().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel backLabel;
    private javax.swing.JTextField cIDText;
    private javax.swing.JTextField cNameText;
    private javax.swing.JTextField courseDesc_Text;
    private javax.swing.JLabel courseDescriptionLabel;
    private javax.swing.JLabel courseDet_Label;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JLabel courseidLabel;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JTextField feeText;
    private javax.swing.JComboBox<String> levelComboBox;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel usr_lbl;
    // End of variables declaration//GEN-END:variables
}
