/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OCRS;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author BryanL
 */
public class Stud_manageprofile extends javax.swing.JFrame {

    /**
     * Creates new form Stud_manageprofile
     */
    public Stud_manageprofile() {
        initComponents();
    }
    public Stud_manageprofile(String name, String id, String deg, String lvl, String uname) {
        initComponents();    
        name_lbl.setText(name);
        id_lbl.setText(id);
        degree_lbl.setText(deg);
        lvl_lbl.setText(lvl);
        usr_lbl.setText(uname);
        try{
            FileReader fr = new FileReader ("Enrollment_List.txt");
            BufferedReader br = new BufferedReader(fr);
            String reader;
            String[] temp;
            reader = br.readLine();
            int i = 0, j = 0;
            if ("testnull".equals(reader)){
                System.out.println("This should not occur, only to handle NullPointerException.");
            }
            else{
                if (reader == null){
                    br.close();
                    fr.close();
                    return;
                }
                else{
                    while (reader.length() != 0) {
                        temp = reader.split(",");
                        if (uname.equals(temp[0])) {
                            course_t1.setValueAt(temp[1], i, j);
                            course_t1.setValueAt(temp[2], i, j+1);
                            i++;
                        }
                        reader = br.readLine();
                        if ("testnull".equals(reader)){
                            System.out.println("This should not occur, only to handle NullPointerException.");
                        }
                        else if(reader == null){
                            br.close();
                            fr.close();
                            return;
                        }                
                    }
                    br.close();
                    fr.close();                    
                }
            }
        } catch (Exception f) {
            JOptionPane.showMessageDialog(null, "System error " + f);
        }        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        course_t = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        degree_lbl = new javax.swing.JLabel();
        lvl_lbl = new javax.swing.JLabel();
        usr_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        man_b = new javax.swing.JButton();
        cancel_b = new javax.swing.JButton();
        name_lbl = new javax.swing.JLabel();
        name_f = new javax.swing.JTextField();
        id_f = new javax.swing.JTextField();
        degree_s = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        level_s = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        course_t1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        course_f = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        course_t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"No courses registered yet", null}
            },
            new String [] {
                "Course", "Course Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(course_t);

        jLabel8.setText("Registered courses:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id_lbl.setText("(ID will be replaced here)");

        degree_lbl.setText("(Degree will be replaced here)");

        lvl_lbl.setText("(Level will be replaced here)");

        usr_lbl.setText("(Username will be replaced here)");

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("M Y   P R O F I L E ");

        jLabel10.setText("Level:");

        jLabel2.setText("Name:");

        jLabel3.setText("ID:");

        jLabel4.setText("Degree:");

        jLabel6.setText("Username:");

        man_b.setText("Save");
        man_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_bActionPerformed(evt);
            }
        });

        cancel_b.setText("Back");
        cancel_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_bActionPerformed(evt);
            }
        });

        name_lbl.setText("(Name will be replaced here)");

        name_f.setForeground(new java.awt.Color(153, 153, 153));
        name_f.setText("Enter new name");
        name_f.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_fFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_fFocusLost(evt);
            }
        });

        id_f.setForeground(new java.awt.Color(153, 153, 153));
        id_f.setText("Enter new ID");
        id_f.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id_fFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                id_fFocusLost(evt);
            }
        });

        degree_s.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Course", "BSc (Hons) Computer Science", "BSc (Hons) Software Engineering", "BSc (Hons) Cyber Security", "BSc (Hons) Intelligent Systems" }));
        degree_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree_sActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField3");

        level_s.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Degree Level", "Level 1", "Level 2", "Level 3", " " }));

        jLabel5.setText("Please enter new details, leave empty if you do not wish to change.");

        jLabel7.setText("Username can not be modified.");

        course_t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"No courses registered yet", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course", "Course Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(course_t1);

        jLabel9.setText("Registered courses:");

        jLabel11.setText("Course Code(s):");

        jLabel12.setText("NOTE: To remove multiple courses separate course codes with \",\".");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Enter course code(s) to unregister course(s).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name_lbl)
                                    .addComponent(id_lbl)
                                    .addComponent(degree_lbl)
                                    .addComponent(lvl_lbl)
                                    .addComponent(id_f)
                                    .addComponent(name_f)
                                    .addComponent(degree_s, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(level_s, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(man_b)
                        .addGap(18, 18, 18)
                        .addComponent(cancel_b))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel6)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(usr_lbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(course_f, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel12))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(degree_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degree_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lvl_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(level_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usr_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(course_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(man_b)
                    .addComponent(cancel_b))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void degree_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree_sActionPerformed

    }//GEN-LAST:event_degree_sActionPerformed

    private void name_fFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_fFocusGained
        if("Enter new name".equals(name_f.getText())){
            name_f.setText("");
            name_f.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_name_fFocusGained

    private void name_fFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_fFocusLost
        if("".equals(name_f.getText())){
            name_f.setText("Enter new name");
            name_f.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_name_fFocusLost

    private void id_fFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id_fFocusGained
        if("Enter new ID".equals(id_f.getText())){
            id_f.setText("");
            id_f.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_id_fFocusGained

    private void id_fFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id_fFocusLost
        if("".equals(id_f.getText())){
            id_f.setText("Enter new ID");
            id_f.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_id_fFocusLost

    private void cancel_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_bActionPerformed
        String uname = usr_lbl.getText();
        Stud_vProfile svp = new Stud_vProfile(uname);
        svp.setVisible(true);
        this.dispose();
        return;
    }//GEN-LAST:event_cancel_bActionPerformed

    private void man_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_bActionPerformed
        String uname, name, id, degree, lvl, course = "", reader;
        String[] temp;
        String line_sep = System.lineSeparator();
        
        uname = usr_lbl.getText();
        name = name_f.getText();
        id = id_f.getText();
        degree = degree_s.getSelectedItem().toString();
        lvl = level_s.getSelectedItem().toString();
        course = course_f.getText().replaceAll(" ", "").toUpperCase();
        
        try{
            FileReader fr = new FileReader("Student_Profile_DB.txt");
            BufferedReader br = new BufferedReader(fr);
            reader = br.readLine();
            while (reader.length() != 0){
                temp = reader.split(",");
                if (uname.equals(temp[4])){
                    if(name.equals("Enter new name")&&id.equals("Enter new ID")&&degree.equals("Select Course")&&lvl.equals("Select Degree Level")&&course.equals("")){
                        br.close();
                        fr.close();
                        JOptionPane.showMessageDialog(null, "No changes made.");
                        return;
                    }
                    else{
                        int return_opt = 0;
                        return_opt = JOptionPane.showConfirmDialog(null, "Confirm change profile details?", "WARNING", JOptionPane.OK_CANCEL_OPTION);                        
                        if(return_opt == JOptionPane.OK_OPTION){
                            br.close();
                            fr.close();
                            Modify_Files mf = new Modify_Files();
                            String status = mf.replaceStudDetails(uname, name, id, degree, lvl, course);
                            if(status.equals("all deleted")){
                                JOptionPane.showMessageDialog(null, "Changes saved!");
                                Stud_vProfile svp = new Stud_vProfile(uname);
                                svp.setVisible(true);
                                this.dispose();
                                return;                                
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Changes saved!"+line_sep+"Unable to remove certain courses, please try again.");
                                Stud_manageprofile smp = new Stud_manageprofile(name,id,degree,lvl,uname);
                                smp.setVisible(true);
                                this.dispose();
                                return;  
                            }
                        }
                        else{
                            br.close();
                            fr.close();
                            return;                           
                        }
                    }
                }
                reader = br.readLine();
                if ("testnull".equals(reader)){
                    System.out.println("This should not occur, only to handle NullPointerException.");
                }
                else if (reader == null){
                    br.close();
                    fr.close();                        
                    break;                                
                }                
            }            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "System error, unable to make changes " + e);
        }
    }//GEN-LAST:event_man_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stud_manageprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stud_manageprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stud_manageprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stud_manageprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stud_manageprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_b;
    private javax.swing.JTextField course_f;
    private javax.swing.JTable course_t;
    private javax.swing.JTable course_t1;
    private javax.swing.JLabel degree_lbl;
    private javax.swing.JComboBox degree_s;
    private javax.swing.JTextField id_f;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox level_s;
    private javax.swing.JLabel lvl_lbl;
    private javax.swing.JButton man_b;
    private javax.swing.JTextField name_f;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel usr_lbl;
    // End of variables declaration//GEN-END:variables
}
