/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OCRS;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author BryanL
 */
public class Stud_mMenu extends javax.swing.JFrame {

    /**
     * Creates new form Stud_mMenu
     */ 
    public Stud_mMenu() {
        initComponents();
    }
    public Stud_mMenu(String uname) {
        initComponents();
        String[] temp;
        try{
            FileReader fr = new FileReader("Student_Profile_DB.txt");
            BufferedReader br = new BufferedReader(fr);
            String reader;
            reader = br.readLine();
            while (reader.length() != 0) {
                temp = reader.split(",");
                if (uname.equals(temp[4])) {
                    usr_lbl.setText(uname);
                    usr_lbl.setVisible(false);
                    name_lbl.setText(temp[0]);
                    br.close();
                    fr.close();                    
                    return;
                }
                reader = br.readLine();
                if ("testnull".equals(reader)){
                    System.out.println("This should not occur, only to handle NullPointerException.");
                }
                else{
                    if(reader == null){
                        br.close();
                        fr.close();                        
                        return;
                    }
                }                
            }
        } catch (Exception f) {
            JOptionPane.showMessageDialog(null, "System error" + f);
        }        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        Viewp_b = new javax.swing.JButton();
        Enrollc_b = new javax.swing.JButton();
        Listc_b = new javax.swing.JButton();
        Viewb_b = new javax.swing.JButton();
        Logout_b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        usr_lbl = new javax.swing.JLabel();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Viewp_b.setText("View Profile");
        Viewp_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viewp_bActionPerformed(evt);
            }
        });

        Enrollc_b.setText("Enroll Course");
        Enrollc_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enrollc_bActionPerformed(evt);
            }
        });

        Listc_b.setText("List Courses");
        Listc_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listc_bActionPerformed(evt);
            }
        });

        Viewb_b.setText("View Bill");
        Viewb_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viewb_bActionPerformed(evt);
            }
        });

        Logout_b.setText("Log Out");
        Logout_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_bActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME");

        name_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_lbl.setText("(name will be replaced here)");

        usr_lbl.setText("(Placeholder for username)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(name_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(usr_lbl)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logout_b, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Viewb_b, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listc_b, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enrollc_b, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Viewp_b, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(usr_lbl)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(name_lbl)
                .addGap(18, 18, 18)
                .addComponent(Viewp_b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Enrollc_b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Listc_b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Viewb_b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout_b, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Viewp_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viewp_bActionPerformed
        String uname = usr_lbl.getText();
        Stud_vProfile svp = new Stud_vProfile(uname);
        svp.setVisible(true);
        this.dispose();
        return;
    }//GEN-LAST:event_Viewp_bActionPerformed

    private void Logout_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_bActionPerformed
        Logout_Display ald = new Logout_Display();
        ald.display_logout_message();
        Login_Page lp = new Login_Page();
        lp.setVisible(true);
        this.dispose();
        return;
    }//GEN-LAST:event_Logout_bActionPerformed

    private void Enrollc_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enrollc_bActionPerformed
        String uname = usr_lbl.getText();
        String courses = "", page = "mm";
        Stud_enrollcourse sec = new Stud_enrollcourse(uname,courses,page);
        sec.setVisible(true);
        this.dispose();
        return;
    }//GEN-LAST:event_Enrollc_bActionPerformed

    private void Listc_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listc_bActionPerformed
        String uname = usr_lbl.getText();
        String profile = "Student";
        List_Courses lc = new List_Courses(uname,profile);
        lc.setVisible(true);
        this.dispose();
        return;
    }//GEN-LAST:event_Listc_bActionPerformed

    private void Viewb_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viewb_bActionPerformed
        String uname = usr_lbl.getText();
        Stud_selectbill ssb = new Stud_selectbill(uname);
        ssb.setVisible(true);
        this.dispose();
        return;
    }//GEN-LAST:event_Viewb_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stud_mMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stud_mMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stud_mMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stud_mMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stud_mMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enrollc_b;
    private javax.swing.JButton Listc_b;
    private javax.swing.JButton Logout_b;
    private javax.swing.JButton Viewb_b;
    private javax.swing.JButton Viewp_b;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel usr_lbl;
    // End of variables declaration//GEN-END:variables
}
