
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DragonKimchi
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu(String id, String fullname) {
        initComponents();
        this.setLocationRelativeTo(null); // This will display the user interface at the middle
        IDLabel.setText(id);
        FullnameLabel.setText(fullname);
    }
//    public Admin(String rem) {
//        initComponents();
//        AdminAccountLabel.setText(rem);
//        this.getContentPane().setBackground(new Color(245,245,245));
//    }

    AdminMenu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageProfile = new javax.swing.JButton();
        ManageCourse = new javax.swing.JButton();
        ViewStudent = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ViewAdmin = new javax.swing.JButton();
        IDLabel = new javax.swing.JLabel();
        FullnameLabel = new javax.swing.JLabel();
        ViewStudentRegisterList = new javax.swing.JButton();
        MakePaymentList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageProfile.setText("Manage Profile");
        manageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProfileActionPerformed(evt);
            }
        });
        getContentPane().add(manageProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 189, 159, -1));

        ManageCourse.setText("Manage Course");
        ManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCourseActionPerformed(evt);
            }
        });
        getContentPane().add(ManageCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 232, 159, -1));

        ViewStudent.setText("View Student List");
        ViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentActionPerformed(evt);
            }
        });
        getContentPane().add(ViewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 318, 159, -1));

        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 442, 159, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 79, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 157, 416, 10));

        ViewAdmin.setText("View Admin List");
        ViewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAdminActionPerformed(evt);
            }
        });
        getContentPane().add(ViewAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 275, 159, -1));

        IDLabel.setForeground(new java.awt.Color(255, 0, 0));
        IDLabel.setText("ID");
        getContentPane().add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 16, -1, -1));

        FullnameLabel.setForeground(new java.awt.Color(255, 0, 0));
        FullnameLabel.setText("Fullname");
        getContentPane().add(FullnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 39, -1, -1));

        ViewStudentRegisterList.setText("View Student Register");
        ViewStudentRegisterList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentRegisterListActionPerformed(evt);
            }
        });
        getContentPane().add(ViewStudentRegisterList, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 361, -1, -1));

        MakePaymentList.setText("Make Payment List");
        MakePaymentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakePaymentListActionPerformed(evt);
            }
        });
        getContentPane().add(MakePaymentList, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 399, 159, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DragonKimchi\\Documents\\NetBeansProjects\\OODJ Assignment\\SaveFile\\Background\\adminMenu.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProfileActionPerformed
        // TODO add your handling code here:
        //go to manage profile menu
        AdminManageProfileMenu ampm = new AdminManageProfileMenu(IDLabel.getText());
        dispose();
        ampm.setVisible(true);
        
    }//GEN-LAST:event_manageProfileActionPerformed

    private void ManageCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCourseActionPerformed
        // TODO add your handling code here:
        dispose();
        CourseMenu cm = new CourseMenu();
        cm.PassVariable(IDLabel.getText(), FullnameLabel.getText());
        cm.setVisible(true);
    }//GEN-LAST:event_ManageCourseActionPerformed

    private void ViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentActionPerformed
        // TODO add your handling code here:
        //view all list of student in Jtable and is able to search with ID
        dispose();
        ViewStudentList vsl = new ViewStudentList();
        vsl.PassVariable(IDLabel.getText(), FullnameLabel.getText());
        vsl.setVisible(true);
    }//GEN-LAST:event_ViewStudentActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        dispose();
        new AdminStudentMenu().setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    private void ViewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAdminActionPerformed
        // TODO add your handling code here:
        //this menu is use to add new admin or new student
        dispose();// this will clear the previous jframe
        ViewAdminList val = new ViewAdminList();
        val.PassVariable(IDLabel.getText(), FullnameLabel.getText());
        val.setVisible(true);
    }//GEN-LAST:event_ViewAdminActionPerformed

    private void ViewStudentRegisterListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentRegisterListActionPerformed
        // TODO add your handling code here:
        dispose();// this will clear the previous jframe
        ViewStudentRegisteredList vsrl = new ViewStudentRegisteredList();
        vsrl.PassVariable(IDLabel.getText(), FullnameLabel.getText());
        vsrl.setVisible(true);
    }//GEN-LAST:event_ViewStudentRegisterListActionPerformed

    private void MakePaymentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakePaymentListActionPerformed
        // TODO add your handling code here:
        dispose();// this will clear the previous jframe
        MakePaymentListMenu mplm = new MakePaymentListMenu();
        mplm.PassVariable(IDLabel.getText(), FullnameLabel.getText());
        mplm.setVisible(true);
    }//GEN-LAST:event_MakePaymentListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FullnameLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton MakePaymentList;
    private javax.swing.JButton ManageCourse;
    private javax.swing.JButton ViewAdmin;
    private javax.swing.JButton ViewStudent;
    private javax.swing.JButton ViewStudentRegisterList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton manageProfile;
    // End of variables declaration//GEN-END:variables
}
