
import java.awt.Color;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DragonKimchi
 */
public class ViewStudentList extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudentList
     */
    int checkSearch = 0;
    StudentClass sc = new StudentClass();
    String ID, fullname, username, password, contact, email, degreeLevel;
    
    public ViewStudentList() {
        initComponents();
        this.setLocationRelativeTo(null); // This will display the user interface at the middle
        String x = "SaveFile/Student.txt";
        sc.View(StudentTable, x);
        this.getContentPane().setBackground(new Color(245,245,245));
        TableColumnModel tcm = StudentTable.getColumnModel();
        tcm.getColumn(0).setPreferredWidth(150);
        tcm.getColumn(1).setPreferredWidth(150);
        tcm.getColumn(2).setPreferredWidth(100);
        tcm.getColumn(3).setPreferredWidth(150);
        tcm.getColumn(4).setPreferredWidth(150);
        tcm.getColumn(5).setPreferredWidth(300);
        tcm.getColumn(6).setPreferredWidth(50);
        EditStudent.setEnabled(false);
        DeleteStudent.setEnabled(false);
    }
    
    String id, fn;
    public void PassVariable(String ID, String fullname)
    {
        id = ID;
        fn = fullname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStudent = new javax.swing.JButton();
        Back = new javax.swing.JToggleButton();
        Search_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        EditStudent = new javax.swing.JButton();
        DeleteStudent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddStudent.setText("Add Student");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Search_text.setText("Search......");
        Search_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Search_textMousePressed(evt);
            }
        });
        Search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_textActionPerformed(evt);
            }
        });
        Search_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_textKeyReleased(evt);
            }
        });

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "ID", "Full Name", "Contact Number", "Email", "Degree Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudentTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(StudentTable);

        EditStudent.setText("Edit Student");
        EditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStudentActionPerformed(evt);
            }
        });

        DeleteStudent.setText("Delete Student");
        DeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Manage Student Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddStudent)
                        .addGap(41, 41, 41)
                        .addComponent(EditStudent)
                        .addGap(71, 71, 71)
                        .addComponent(DeleteStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Search_text, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(295, 295, 295)
                                .addComponent(Back)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteStudent)
                        .addComponent(EditStudent))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddStudent)
                        .addComponent(Search_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        // TODO add your handling code here:
        dispose();
        AddStudentMenu asm = new AddStudentMenu();
        asm.PassVariable(id, fn);
        asm.setVisible(true);
    }//GEN-LAST:event_AddStudentActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminMenu am = new AdminMenu(id, fn);
        am.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void Search_textMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_textMousePressed
        // TODO add your handling code here:
        Search_text.setText("");
    }//GEN-LAST:event_Search_textMousePressed

    private void Search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_textActionPerformed

    private void Search_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_textKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)StudentTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(table);
        StudentTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + Search_text.getText()));

        //infrom that search is trigger
        checkSearch = 1;
    }//GEN-LAST:event_Search_textKeyReleased

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentTableMouseClicked

    private void StudentTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMousePressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)StudentTable.getModel();
        int selectedRowIndex = StudentTable.getSelectedRow();

        //if got search then the view and the model will not match, use convertRowIndexToModel method to convert the index of the view to the model
        //Eg in view it is 1, model is 6
        if (checkSearch == 1)
        {
            selectedRowIndex = StudentTable.convertRowIndexToModel(selectedRowIndex);
            checkSearch = 0;
        }

        //String code, name, lv, fees, duration;
        username = (model.getValueAt(selectedRowIndex, 0).toString());
        password = (model.getValueAt(selectedRowIndex, 1).toString());
        ID = (model.getValueAt(selectedRowIndex, 2).toString());
        fullname = (model.getValueAt(selectedRowIndex, 3).toString());
        contact = (model.getValueAt(selectedRowIndex, 4).toString());
        email = (model.getValueAt(selectedRowIndex, 5).toString());
        degreeLevel = (model.getValueAt(selectedRowIndex, 6).toString());

        EditStudent.setEnabled(true);
        DeleteStudent.setEnabled(true);
    }//GEN-LAST:event_StudentTableMousePressed

    private void EditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStudentActionPerformed
        // TODO add your handling code here:
        //call CourseClass to do edit
        EditStudentMenu es = new EditStudentMenu();
        es.setEditStudent(ID, fullname, username, password, contact, email, degreeLevel);
        es.PassVariable(id, fn);
        es.setVisible(true);
        dispose();

    }//GEN-LAST:event_EditStudentActionPerformed

    private void DeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentActionPerformed
        // TODO add your handling code here:
        DeleteStudentMenu dsm = new DeleteStudentMenu();
        dsm.setDeleteStudent(ID, fullname, username, password, contact, email, degreeLevel);
        dsm.PassVariable(id, fn);
        dsm.setVisible(true);
        dispose();
    }//GEN-LAST:event_DeleteStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudentList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudent;
    private javax.swing.JToggleButton Back;
    private javax.swing.JButton DeleteStudent;
    private javax.swing.JButton EditStudent;
    private javax.swing.JTextField Search_text;
    private javax.swing.JTable StudentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
