/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ivandroassignment;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author hp
 */
public class Admin_Menu extends javax.swing.JFrame {

    
    public Admin_Menu() {
        initComponents();
        currentDate(); // Function for the system date and time
    }
    public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        jlabelDate.setText(day+"/"+(month+1) +"/"+year);
        
        //Time
      
        
        int minutes = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        jLabelTime.setText(hour+":"+(minutes));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAdminMenuOption = new javax.swing.JLabel();
        jButtonRegistration = new javax.swing.JButton();
        jButtonViewRecords = new javax.swing.JButton();
        jButtonSearchRecords = new javax.swing.JButton();
        jButtonDeleteRecords = new javax.swing.JButton();
        jButtonModifyRecords = new javax.swing.JButton();
        jButtonModifyAttendance = new javax.swing.JButton();
        jButtonGoback = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelAdminMenu = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jlabelDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelAdminMenuOption.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelAdminMenuOption.setText("Please Select an Option:");

        jButtonRegistration.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonRegistration.setText("Registration");
        jButtonRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrationActionPerformed(evt);
            }
        });

        jButtonViewRecords.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonViewRecords.setText("View Records");
        jButtonViewRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewRecordsActionPerformed(evt);
            }
        });

        jButtonSearchRecords.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonSearchRecords.setText("Search Records");
        jButtonSearchRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchRecordsActionPerformed(evt);
            }
        });

        jButtonDeleteRecords.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonDeleteRecords.setText("Delete Records");
        jButtonDeleteRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRecordsActionPerformed(evt);
            }
        });

        jButtonModifyRecords.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonModifyRecords.setText("Modify Records");
        jButtonModifyRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyRecordsActionPerformed(evt);
            }
        });

        jButtonModifyAttendance.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonModifyAttendance.setText("Modify Attendance");
        jButtonModifyAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyAttendanceActionPerformed(evt);
            }
        });

        jButtonGoback.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonGoback.setText("Go Back");
        jButtonGoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGobackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabelAdminMenu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelAdminMenu.setText("Admin Menu");

        jLabelTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelTime.setText("Time");

        jlabelDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlabelDate.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabelAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabelAdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTime)
                    .addComponent(jlabelDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdminMenuOption, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonViewRecords, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSearchRecords, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModifyAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModifyRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonGoback)
                .addGap(18, 18, 18))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAdminMenuOption, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistration)
                    .addComponent(jButtonDeleteRecords))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewRecords)
                    .addComponent(jButtonModifyRecords))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchRecords)
                    .addComponent(jButtonModifyAttendance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonGoback)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGobackActionPerformed
        // TODO add your handling code here:
        // Allows the program to go back to the previous window
        close();
        System_Menu goback = new System_Menu();
        goback.setVisible(true);
    }//GEN-LAST:event_jButtonGobackActionPerformed

    private void jButtonRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrationActionPerformed
        // TODO add your handling code here:
        close();
                    Admin_Registration openwindow = new Admin_Registration();
                    openwindow.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrationActionPerformed

    private void jButtonViewRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewRecordsActionPerformed
        // TODO add your handling code here:
        close();
                    Admin_ViewRecords openwindow = new Admin_ViewRecords();
                    openwindow.setVisible(true);
        
    }//GEN-LAST:event_jButtonViewRecordsActionPerformed

    private void jButtonSearchRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchRecordsActionPerformed
        // TODO add your handling code here:
        close();
                    Admin_OptionSearch openwindow = new Admin_OptionSearch();
                    openwindow.setVisible(true);
    }//GEN-LAST:event_jButtonSearchRecordsActionPerformed

    private void jButtonModifyAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyAttendanceActionPerformed
        // TODO add your handling code here:
         close();
                    Admin_ModifyAttendance openwindow = new Admin_ModifyAttendance();
                    openwindow.setVisible(true);
    }//GEN-LAST:event_jButtonModifyAttendanceActionPerformed

    private void jButtonDeleteRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRecordsActionPerformed
        // TODO add your handling code here:
         close();
                    Admin_DeleteRecords openwindow = new Admin_DeleteRecords();
                    openwindow.setVisible(true);
    }//GEN-LAST:event_jButtonDeleteRecordsActionPerformed

    private void jButtonModifyRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyRecordsActionPerformed
        // TODO add your handling code here:
         close();
                    Admin_OptionUpdate openwindow = new Admin_OptionUpdate();
                    openwindow.setVisible(true);
    }//GEN-LAST:event_jButtonModifyRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteRecords;
    private javax.swing.JButton jButtonGoback;
    private javax.swing.JButton jButtonModifyAttendance;
    private javax.swing.JButton jButtonModifyRecords;
    private javax.swing.JButton jButtonRegistration;
    private javax.swing.JButton jButtonSearchRecords;
    private javax.swing.JButton jButtonViewRecords;
    private javax.swing.JLabel jLabelAdminMenu;
    private javax.swing.JLabel jLabelAdminMenuOption;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabelDate;
    // End of variables declaration//GEN-END:variables

// Creation of the void Close to close the windows
    private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }
}
