/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OCRS;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author audrey
 */
public class admin_mMenu extends javax.swing.JFrame {

    /** Creates new form admin_mMenu */
    String logout_message = "You have successfully logged out!";
    public admin_mMenu() {
        initComponents();
    }
    private String uname;
    
    public admin_mMenu(String uname) {
        initComponents();
        String[] temp;
        usr_lbl.setText(uname);
        usr_lbl.setVisible(false);
        this.uname = uname;
        try {
            FileReader fr = new FileReader("Admin_Profile_DB.txt");
            BufferedReader br = new BufferedReader(fr);
            String reader;
            reader = br.readLine();
            while (reader.length()!=0) {
                temp = reader.split(",");
                if(uname.equals(temp[3])) {
                    nameLabel.setText("Welcome, " + temp[0] + "!");
                    br.close();
                    fr.close();
                    return;
                }
                
                reader = br.readLine();
            }
        }
        catch(Exception f) {
            JOptionPane.showMessageDialog(null, "System error" + f);    
        }  
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mProfileButton = new javax.swing.JButton();
        courseButton = new javax.swing.JButton();
        listStudButton = new javax.swing.JButton();
        logOutLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        usr_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mProfileButton.setText("View Profile");
        mProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProfileButtonActionPerformed(evt);
            }
        });

        courseButton.setText("Course");
        courseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseButtonActionPerformed(evt);
            }
        });

        listStudButton.setText("List Of Students");
        listStudButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudButtonActionPerformed(evt);
            }
        });

        logOutLabel1.setText("Log Out");
        logOutLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutLabel1MouseEntered(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("name will be replaced");

        usr_lbl.setText("(Placeholder for username)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(usr_lbl)
                .addGap(51, 51, 51)
                .addComponent(logOutLabel1)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listStudButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(courseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logOutLabel1)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usr_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(courseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listStudButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void mProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProfileButtonActionPerformed
        // TODO add your handling code here:
        String uname = usr_lbl.getText();
        admin_mProfile_mMenu a = new admin_mProfile_mMenu(uname);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mProfileButtonActionPerformed

    private void courseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseButtonActionPerformed
        // TODO add your handling code here:
        String uname = usr_lbl.getText();
        String profile = "Admin";
        List_Courses lc = new List_Courses(uname, profile);
        lc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_courseButtonActionPerformed

    private void logOutLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabel1MouseClicked
        // TODO add your handling code here:
        Logout_Display ald = new Logout_Display();
        ald.display_logout_message();
        Login_Page l = new Login_Page();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutLabel1MouseClicked

    private void logOutLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabel1MouseEntered
        // TODO add your handling code here:
        Font original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_logOutLabel1MouseEntered

    private void logOutLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabel1MouseExited
        // TODO add your handling code here:
        Font original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_logOutLabel1MouseExited

    private void listStudButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudButtonActionPerformed
        // TODO add your handling code here:
        admin_studList asl = new admin_studList(uname);
        asl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listStudButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_mMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_mMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_mMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_mMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_mMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton courseButton;
    private javax.swing.JButton listStudButton;
    private javax.swing.JLabel logOutLabel1;
    private javax.swing.JButton mProfileButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel usr_lbl;
    // End of variables declaration//GEN-END:variables

}
