/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OCRS;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author BryanL
 */
public class admin_modCourse extends javax.swing.JFrame {

    /**
     * Creates new form admin_modCourse
     */
    public admin_modCourse() {
        initComponents();
    }
    public admin_modCourse(String uname, String coursen, String coursec, String lvl, String coursed, String fee) {
        initComponents();
        usr_lbl.setText(uname);
        usr_lbl.setVisible(false);
        coursen_lbl.setText(coursen);
        coursec_lbl.setText(coursec);
        lvl_lbl.setText(lvl);
        coursed_lbl.setText(coursed);
        fee_lbl.setText(fee);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usr_lbl = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        courseDescriptionLabel = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        coursen_f = new javax.swing.JTextField();
        coursec_f = new javax.swing.JTextField();
        fee_f = new javax.swing.JTextField();
        courseDet_Label = new javax.swing.JLabel();
        lvl_s = new javax.swing.JComboBox<>();
        courseidLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        coursen_lbl = new javax.swing.JLabel();
        coursec_lbl = new javax.swing.JLabel();
        lvl_lbl = new javax.swing.JLabel();
        fee_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursed_f = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursed_lbl = new javax.swing.JTextArea();

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usr_lbl.setText("(placeholder for username)");

        backLabel.setText("Back to Course List");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLabelMouseExited(evt);
            }
        });

        levelLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        levelLabel.setText("Level:");

        courseDescriptionLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        courseDescriptionLabel.setText("Course Description:");

        feeLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        feeLabel.setText("Fee:");

        coursen_f.setForeground(new java.awt.Color(153, 153, 153));
        coursen_f.setText("Enter new course name");
        coursen_f.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                coursen_fFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                coursen_fFocusLost(evt);
            }
        });

        coursec_f.setForeground(new java.awt.Color(153, 153, 153));
        coursec_f.setText("Enter new course code");
        coursec_f.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                coursec_fFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                coursec_fFocusLost(evt);
            }
        });

        fee_f.setForeground(new java.awt.Color(153, 153, 153));
        fee_f.setText("Enter new course fee");
        fee_f.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fee_fFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fee_fFocusLost(evt);
            }
        });
        fee_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fee_fActionPerformed(evt);
            }
        });

        courseDet_Label.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 24)); // NOI18N
        courseDet_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseDet_Label.setText("Modify Course Details");

        lvl_s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select new course level", "Level 1", "Level 2", "Level 3" }));
        lvl_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl_sActionPerformed(evt);
            }
        });

        courseidLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        courseidLabel.setText("Course Name:");

        courseNameLabel.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 13)); // NOI18N
        courseNameLabel.setText("Course Code:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        coursen_lbl.setText("(Course name will be replaced here)");

        coursec_lbl.setText("(Course code will be replaced here)");

        lvl_lbl.setText("(Course level will be replaced here)");

        fee_lbl.setText("(Course fee will be replaced here)");

        coursed_f.setColumns(20);
        coursed_f.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        coursed_f.setForeground(new java.awt.Color(153, 153, 153));
        coursed_f.setLineWrap(true);
        coursed_f.setRows(5);
        coursed_f.setText("Enter new course description");
        coursed_f.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                coursed_fFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                coursed_fFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(coursed_f);

        coursed_lbl.setEditable(false);
        coursed_lbl.setColumns(20);
        coursed_lbl.setLineWrap(true);
        coursed_lbl.setRows(5);
        jScrollPane2.setViewportView(coursed_lbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(courseidLabel)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coursen_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(coursen_f, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(courseDescriptionLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelLabel)
                                    .addComponent(feeLabel))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fee_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lvl_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lvl_s, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fee_f, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(courseNameLabel)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coursec_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coursec_f, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usr_lbl)
                        .addGap(55, 55, 55)
                        .addComponent(backLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(courseDet_Label)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backLabel)
                    .addComponent(usr_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseDet_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseidLabel)
                    .addComponent(coursen_lbl))
                .addGap(0, 0, 0)
                .addComponent(coursen_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseNameLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coursec_lbl)
                        .addGap(0, 0, 0)
                        .addComponent(coursec_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(lvl_lbl))
                .addGap(0, 0, 0)
                .addComponent(lvl_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feeLabel)
                    .addComponent(fee_lbl))
                .addGap(1, 1, 1)
                .addComponent(fee_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseDescriptionLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(resetButton))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        String uname = usr_lbl.getText();
        String profile = "Admin";
        List_Courses lc = new List_Courses(uname, profile);
        lc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    private void backLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseEntered
        // TODO add your handling code here:
        Font original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_backLabelMouseEntered

    private void backLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseExited
        // TODO add your handling code here:
        Font original = evt.getComponent().getFont();
        Map attributes = original.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        evt.getComponent().setFont(original.deriveFont(attributes));
    }//GEN-LAST:event_backLabelMouseExited

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String oldcoursen, coursen, coursec, lvl, fee, coursed;

        oldcoursen = coursen_lbl.getText();
        coursen = coursen_f.getText();
        coursec = coursec_f.getText();
        lvl = lvl_s.getSelectedItem().toString();
        fee = fee_f.getText();
        coursed = coursed_f.getText().replaceAll("\\r\\n|\\r|\\n", " ");

        try{
            if(coursen.equals("Enter new course name")&&coursec.equals("Enter new course code")&&lvl.equals("Select new course level")&&fee.equals("Enter new course fee")&&coursed.equals("Enter new course description")){
                JOptionPane.showMessageDialog(null, "No changes made.");
                return;
            }
            else{
                int return_opt = 0;
                return_opt = JOptionPane.showConfirmDialog(null, "Confirm change course details?", "WARNING", JOptionPane.OK_CANCEL_OPTION);                        
                if(return_opt == JOptionPane.OK_OPTION){
                    Add_del_mod_course admc = new Add_del_mod_course();
                    admc.modCourse(oldcoursen, coursen, coursec, lvl, coursed, fee);
                    JOptionPane.showMessageDialog(null, "Changes saved!");
                }
                else{
                    return;                           
                }
            }       
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "System error, unable to make changes " + e);
        }

        String uname = usr_lbl.getText();
        String profile = "Admin";
        List_Courses lc = new List_Courses(uname, profile);
        lc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        String uname = usr_lbl.getText();
        String coursen = coursen_lbl.getText();
        String coursec = coursec_lbl.getText();
        String lvl = lvl_lbl.getText();
        String coursed = coursed_lbl.getText();
        String fee = fee_lbl.getText();
        admin_modCourse amc = new admin_modCourse (uname, coursen, coursec, lvl, coursed, fee);
        amc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void lvl_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvl_sActionPerformed

    private void fee_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fee_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fee_fActionPerformed

    private void coursen_fFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coursen_fFocusGained
        if("Enter new course name".equals(coursen_f.getText())){
            coursen_f.setText("");
            coursen_f.setForeground(Color.BLACK);
        }        
    }//GEN-LAST:event_coursen_fFocusGained

    private void coursen_fFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coursen_fFocusLost
        if("".equals(coursen_f.getText())){
            coursen_f.setText("Enter new course name");
            coursen_f.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_coursen_fFocusLost

    private void coursec_fFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coursec_fFocusGained
        if("Enter new course code".equals(coursec_f.getText())){
            coursec_f.setText("");
            coursec_f.setForeground(Color.BLACK);
        }        
    }//GEN-LAST:event_coursec_fFocusGained

    private void coursec_fFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coursec_fFocusLost
        if("".equals(coursec_f.getText())){
            coursec_f.setText("Enter new course code");
            coursec_f.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_coursec_fFocusLost

    private void fee_fFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fee_fFocusGained
        if("Enter new course fee".equals(fee_f.getText())){
            fee_f.setText("");
            fee_f.setForeground(Color.BLACK);
        }    
    }//GEN-LAST:event_fee_fFocusGained

    private void fee_fFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fee_fFocusLost
        if("".equals(fee_f.getText())){
            fee_f.setText("Enter new course fee");
            fee_f.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_fee_fFocusLost

    private void coursed_fFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coursed_fFocusGained
        if("Enter new course description".equals(coursed_f.getText())){
            coursed_f.setText("");
            coursed_f.setForeground(Color.BLACK);
        }  
    }//GEN-LAST:event_coursed_fFocusGained

    private void coursed_fFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coursed_fFocusLost
        if("".equals(coursed_f.getText())){
            coursed_f.setText("Enter new course description");
            coursed_f.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_coursed_fFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_modCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_modCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_modCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_modCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_modCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel courseDescriptionLabel;
    private javax.swing.JLabel courseDet_Label;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField coursec_f;
    private javax.swing.JLabel coursec_lbl;
    private javax.swing.JTextArea coursed_f;
    private javax.swing.JTextArea coursed_lbl;
    private javax.swing.JLabel courseidLabel;
    private javax.swing.JTextField coursen_f;
    private javax.swing.JLabel coursen_lbl;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JTextField fee_f;
    private javax.swing.JLabel fee_lbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel lvl_lbl;
    private javax.swing.JComboBox<String> lvl_s;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel usr_lbl;
    // End of variables declaration//GEN-END:variables
}
